{% set name = "pymt_topography" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 976027467daca18c1ac907b9d2f8e44ed1b399f464555fe9d72f8975a59f980d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9
    - pip
    - meson-python
    - meson
    - ninja
  run:
    - python >=3.9
    - bmi-topography

test:
  requires:
    - bmi-tester
  imports:
    - pymt_topography
  source_files:
    - examples
  commands:
    - bmi-test pymt_topography.bmi:Topography --config-file=examples/bmi-topography.yaml --root-dir=examples -vvv  # [unix]

about:
  home: https://github.com/pymt-lab/pymt_topography
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Provides access to land elevation data within *pymt*.
  description: |
    *pymt_topography* is a Python package for a Python Modeling Toolkit (*pymt*)
    component that provides access to land elevation data through the
    OpenTopography REST API.
  doc_url: https://pymt-topography.readthedocs.io
  dev_url: https://github.com/pymt-lab/pymt_topography

extra:
  recipe-maintainers:
    - mdpiper
