{% set python_min = "3.12" %}
{% set name = "pymt_topography" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ee72dacf2636b36d75df8773c2ca243b5a058f2549901ace34cf69f5798fe5c8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - meson-python
    - meson
    - ninja
  run:
    - python >={{ python_min }}
    - bmi-topography

test:
  requires:
    - bmi-tester
    - python {{ python_min }}
  imports:
    - pymt_topography
  source_files:
    - examples
  commands:
    - bmi-test pymt_topography.bmi:Topography --config-file=${PWD}/examples/bmi-topography.yaml --root-dir=examples -vvv  # [unix]

about:
  home: https://csdms.colorado.edu
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Provides access to land elevation data within *pymt*.
  description: |
    *pymt_topography* is a Python package for a Python Modeling Toolkit (*pymt*)
    component that provides access to land elevation data through the
    OpenTopography REST API.
  doc_url: https://pymt-topography.readthedocs.io
  dev_url: https://github.com/pymt-lab/pymt_topography

extra:
  recipe-maintainers:
    - mdpiper
